author:
  - Valentin Robert <valentin.robert.42@gmail.com>

default-extensions: []

dependencies:
  - base ^>= 4.13.0.0
  - string-interpolate

executables:
  day01:
    main: Main.hs
    source-dirs: day01
    dependencies: []

ghc-options:
  - -Wall
  - -Werror

library:

  dependencies: []

  exposed-modules: []

  other-modules: []

  source-dirs: lib

license: BSD3

name: advent-of-code

tests:
  test-day01:
    main: Main.hs
    source-dirs: day01/test
    dependencies:
      - advent-of-code
    other-modules: []

version: 2020.12.1
