author:
  - Valentin Robert <valentin.robert.42@gmail.com>

default-extensions: []

dependencies:
  - adjunctions
  - base ^>= 4.13.0.0
  - binary-literal-qq
  - comonad
  - cond
  - containers
  - distributive
  - extra
  - finite-typelits
  - lens
  - megaparsec
  - MissingH
  - polysemy
  - polysemy-plugin
  - reflection
  - safe
  - string-interpolate
  - vector-sized

executables:
  day01:
    main: Main.hs
    source-dirs: day01
    dependencies:
      - advent-of-code
  day02:
    main: Main.hs
    source-dirs: day02
    dependencies: []
  day03:
    main: Main.hs
    source-dirs: day03
    dependencies: []
  day04:
    main: Main.hs
    source-dirs: day04
    dependencies: []
  day05:
    main: Main.hs
    source-dirs: day05
    dependencies: []
  day06:
    main: Main.hs
    source-dirs: day06
    dependencies: []
  day07:
    main: Main.hs
    source-dirs: day07
    dependencies: []
  day08:
    main: Main.hs
    source-dirs: day08
    dependencies: []
  day09:
    main: Main.hs
    source-dirs: day09
    dependencies:
      - advent-of-code
  day10:
    main: Main.hs
    source-dirs: day10
    dependencies: []
  day11:
    main: Main.hs
    source-dirs: day11
    dependencies:
      - advent-of-code
  day12:
    main: Main.hs
    source-dirs: day12
    dependencies: []
  day13:
    main: Main.hs
    source-dirs: day13
    dependencies:
      - advent-of-code

ghc-options:
  - -flate-specialise
  - -fplugin=Polysemy.Plugin
  - -fspecialise-aggressively
  - -O2
  - -Wall

library:

  dependencies: []

  exposed-modules:
    - AdventOfCode.Both
    - AdventOfCode.Tuples

  other-modules: []

  source-dirs: lib

license: BSD3

name: advent-of-code

version: 2020.12.1
