author:
  - Valentin Robert <valentin.robert.42@gmail.com>

default-extensions: []

dependencies:
  - base ^>= 4.13.0.0
  - binary-literal-qq
  - cond
  - lens
  - megaparsec
  - MissingH
  - string-interpolate

executables:
  day01:
    main: Main.hs
    source-dirs: day01
    dependencies: []
  day02:
    main: Main.hs
    source-dirs: day02
    dependencies: []
  day03:
    main: Main.hs
    source-dirs: day03
    dependencies: []
  day04:
    main: Main.hs
    source-dirs: day04
    dependencies: []
  day05:
    main: Main.hs
    source-dirs: day05
    dependencies: []
  day06:
    main: Main.hs
    source-dirs: day06
    dependencies: []

ghc-options:
  - -Wall

library:

  dependencies: []

  exposed-modules: []

  other-modules: []

  source-dirs: lib

license: BSD3

name: advent-of-code

version: 2020.12.1
